syntax = "proto3";

package sfc_invite;

import "Messages/Invite/Game/Player/Get/get_game_player_invite_request.proto";
import "Messages/Invite/Game/Player/Get/get_game_player_invite_response.proto";
import "Messages/Invite/Game/Player/Find/get_game_player_invites_request.proto";
import "Messages/Invite/Game/Player/Find/get_game_player_invites_response.proto";

option csharp_namespace = "SFC.Invite.Contracts.Services";

service GamePlayerInviteService {
    rpc GetGamePlayerInvite(GetGamePlayerInviteRequest) returns (GetGamePlayerInviteResponse);
    rpc GetGamePlayerInvites(GetGamePlayerInvitesRequest) returns (GetGamePlayerInvitesResponse);
}