<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SFC.Invite.Contracts</PackageId>
    <Version>0.0.3</Version>
    <Authors>Andrii Kryvoruk</Authors>
    <Company>SFC</Company>
    <Product>SFC</Product>
    <PackageTags>Street Football Club;SFC;Invite;Contracts</PackageTags>
    <Description>
      Contracts from Invite service for SFC project
    </Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.29.3" />
    <PackageReference Include="Grpc.Core.Api" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.69.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Enums\sorting_direction.proto" />
    <Protobuf Include="Headers\auditable_header.proto" />
    <Protobuf Include="Headers\pagination_header.proto" />
    <Protobuf Include="Messages\Invite\Data\GetAll\get_all_invite_data_request.proto" />
    <Protobuf Include="Messages\Invite\Data\GetAll\get_all_invite_data_response.proto" />
    <Protobuf Include="Messages\Invite\Game\Team\Find\Filters\get_game_team_invites_filter.proto" />
    <Protobuf Include="Messages\Invite\Game\Team\Find\get_game_team_invites_request.proto" />
    <Protobuf Include="Messages\Invite\Game\Team\Find\get_game_team_invites_response.proto" />
    <Protobuf Include="Messages\Invite\Game\Team\Get\get_game_team_invite_request.proto" />
    <Protobuf Include="Messages\Invite\Game\Team\Get\get_game_team_invite_response.proto" />
    <Protobuf Include="Messages\Invite\Game\Player\Find\Filters\get_game_player_invites_filter.proto" />
    <Protobuf Include="Messages\Invite\Game\Player\Find\get_game_player_invites_request.proto" />
    <Protobuf Include="Messages\Invite\Game\Player\Find\get_game_player_invites_response.proto" />
    <Protobuf Include="Messages\Invite\Game\Player\Get\get_game_player_invite_request.proto" />
    <Protobuf Include="Messages\Invite\Game\Player\Get\get_game_player_invite_response.proto" />
    <Protobuf Include="Messages\Invite\Team\Player\Find\Filters\get_team_player_invites_filter.proto" />
    <Protobuf Include="Messages\Invite\Team\Player\Find\get_team_player_invites_request.proto" />
    <Protobuf Include="Messages\Invite\Team\Player\Find\get_team_player_invites_response.proto" />
    <Protobuf Include="Messages\Invite\Team\Player\Get\get_team_player_invite_request.proto" />
    <Protobuf Include="Messages\Invite\Team\Player\Get\get_team_player_invite_response.proto" />
    <Protobuf Include="Models\Common\pagination.proto" />
    <Protobuf Include="Models\Common\range_limit.proto" />
    <Protobuf Include="Models\Common\sorting.proto" />
    <Protobuf Include="Models\Invite\Data\data_value.proto" />
    <Protobuf Include="Models\Invite\Game\Team\game_team_invite.proto" />
    <Protobuf Include="Models\Invite\Game\Player\game_player_invite.proto" />
    <Protobuf Include="Models\Invite\Team\Player\team_player_invite.proto" />
    <Protobuf Include="Services\game_team_invite_service.proto" />
    <Protobuf Include="Services\invite_data_service.proto" />
    <Protobuf Include="Services\game_player_invite_service.proto" />
    <Protobuf Include="Services\team_player_invite_service.proto" />
  </ItemGroup>

</Project>
